name: Application CI

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'app.py'
      - 'templates/**'
      - 'static/**'
      - 'requirements.txt'
      - 'Dockerfile'
      - 'tests/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'app.py'
      - 'templates/**'
      - 'static/**'
      - 'requirements.txt'
      - 'Dockerfile'
      - 'tests/**'

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run tests
      run: |
        pytest tests/

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: ecs-app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max